//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jakiekieszonkowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_province
    {
        public int Id_history_province { get; set; }
        public double Average { get; set; }
        public double Median { get; set; }
        public System.DateTime Date { get; set; }
        public int Entries_amount { get; set; }
        public double Standard_deviation { get; set; }
    }
}
