//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jakiekieszonkowe_api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child_pocket_money_option
    {
        public int Id_child_pocket_money_option { get; set; }
        public int Id_child { get; set; }
        public int Id_pocket_money_option { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Pocket_money_option Pocket_money_option { get; set; }
    }
}
