//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jakiekieszonkowe_api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Likes = new HashSet<Like>();
        }
    
        public int Id_comment { get; set; }
        public Nullable<int> Id_city { get; set; }
        public Nullable<int> Id_province { get; set; }
        public int Id_user { get; set; }
        public string Content { get; set; }
        public int Likes_amount { get; set; }
        public System.DateTime Creation_date { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
        public virtual Province Province { get; set; }
    }
}
